#' METNordic input for SWAP
#'
#' This function converts Meteo data from MET Nordic into a SWAP-compatible
#' format. Note: need to use `metnordic_csv()` to create proper input for this
#' function.
#'
#' @param dldir download directory containing data and metadata, as generated by `metnordic_extract()`
#' @param outpath desired location for the swap .met file to be written
#' @param timescale "daily" or "hourly". (hourly not supported yet)
#' @param verbose print some stuff to console?
#' @param name name of the extracted point, as defined in `metnordic_extract()`
#'
#' @returns path to written .met file
#' @export
#'
#' @seealso [metnordic_extract()]
#' @importFrom readr read_csv write_csv
#' @importFrom dplyr %>% group_by mutate select distinct left_join ungroup all_of
#' @importFrom crayon green italic
#' @importFrom lubridate date day month year
#' @importFrom stringr str_pad
swap_metnordic <- function(dldir, name, outpath, timescale = "daily", verbose = FALSE){
  .data <- NULL # R CMD CHECK appeasement
  # parsing paths
  dl_path <- paste0(dldir, "/METNORDIC_point_", name, ".csv")
  meta_path <- paste0(dldir, "/METNORDIC_meta_", name, ".csv")

  # checking if files exist
  if(file.exists(dl_path) == FALSE){
    stop("input file does not exist: \n >> '", dl_path, "'\n make sure to download it using `metnordic_csv()`")
  }

  if(file.exists(meta_path) == FALSE){
    stop("meta file does not exist: \n >> '", meta_path, "'\n make sure to download data using `metnordic_csv()`")
  }

  ## DATE and TIME
  if (timescale == "hourly") {
    stop(
      "This has not been implemented yet because I don't want to deal with the *.001 *.002 *.003 headache."
    )
  } else{
    if (timescale != "daily") {
      stop("timescale parameter not recognized!")
    }
  }

  # reading in data
  indf <- readr::read_csv(dl_path, show_col_types = F)

  ## VALIDATE IF ALL COLUMNS ARE THERE?
  required_columns <- c(
    "date",
    "air_temperature_2m",
    "integral_of_surface_downwelling_shortwave_flux_in_air_wrt_time",
    "precipitation_amount",
    "relative_humidity_2m",
    "wind_speed_10m"
  )
  colcheck <- required_columns %in% (indf %>% colnames()) %>% all()
  if (colcheck == FALSE) {
    stop(
      "not all required columns are present! you are missing:\n",
      required_columns[(required_columns %in% (indf %>% colnames())) == FALSE] %>%  paste0(collapse = ", ")
    )
  }

  # Check that rswap is installed
  if ("rswap" %in% utils::installed.packages()) {
    # if it is installed, check if it is loaded
    if ("rswap" %in% (.packages())) {
      # it is loaded:
      if (verbose) {
        cat(green(italic("rswap already loaded!\n")))
      }
    } else{
      if (verbose){cat(green(italic("loading rswap\n")))}
      # it is not loaded, then load it
      requireNamespace("rswap")
    }
    # it is not installed? then require the user to install it.
  } else{
    stop(
      "rswap is required for this function, please install it.
         \n https://moritzshore.github.io/rswap/"
    )
  }

  ### RADIATION
  # SWAP RAD is shortwave radiation in kJ/m2.
  # MetNordic units are W/m2/s
  # conversion is therefore just 0.001 since J = W/s
  indf$hRAD <- indf$integral_of_surface_downwelling_shortwave_flux_in_air_wrt_time * 0.001

  ### TEMP
  # Simple conversion, K to C
  indf$hTEMP <- indf$air_temperature_2m - 273.15

  ### HUM
  ## MetNordic: in RH
  ## SWAP: in kPa (vapour pressure)
  ## using rswap to do it. see > ?rswap::est_avp()
  indf$hHUM <- rswap::est_avp(indf$hTEMP, indf$hTEMP, rh = indf$relative_humidity_2m*100)

  ### WIND
  ## No conversion necessary: m/s -> m/s
  indf$hWIND <- indf$wind_speed_10m

  ### Rain
  ## mm --> mm, no conversion necessary
  indf$hRAIN <- indf$precipitation_amount

  ### Selecting out variables
  swapcols <- c("date", "hRAD", "hTEMP", "hHUM","hWIND", "hRAIN")
  # rcmd check appeastment

  SWAP_INPUT_DF <- indf %>% dplyr::select(all_of(swapcols))
  DATE <- hRAD  <- hTEMP <- hHUM <- hWIND <- hRAIN <- WET <- NULL
  ### CONVERSION TO DAILY
  keep_these <- c("DATE", "RAD", "Tmin", "Tmax", "HUM", "WIND", "RAIN")
  SWAP_INPUT_DF$DATE <- lubridate::date(SWAP_INPUT_DF$date)
  SWAP_INPUT_DF <- SWAP_INPUT_DF %>% group_by(DATE) %>% mutate(
    RAD = sum(hRAD, na.rm = T) %>% round(2),
    Tmin = min(hTEMP, na.rm = T) %>% round(2),
    Tmax = max(hTEMP, na.rm = T) %>% round(2),
    HUM = mean(hHUM, na.rm = T) %>% round(2),
    WIND = mean(hWIND, na.rm = T) %>% round(2),
    RAIN = sum(hRAIN, na.rm = T) %>% round(2)
  ) %>%
    select(all_of(keep_these)) %>% distinct()

  # reference ET, in mm -99.0 should indicate no data
  # we don't need this since we want to use SWAP calculated ET
  SWAP_INPUT_DF$ETref <- -99.0

  ### Rainfall intensity.
  # to my knowledge, WET is the fraction of the day in which it rained.
  indf$DATE <- lubridate::date(indf$date)
  # the cutoff of 0.01 is kind of arbitraty, but metnordic often has extremely low
  # precipitation values, which count as rain, but are near 0. So this ignores
  # them.
  indf<-indf %>% mutate(qrain = ifelse(precipitation_amount >= 0.01, yes = 1, no = 0))
  WET <- indf %>% group_by(DATE) %>% mutate(WET = ((sum(qrain, na.rm = T)/24) %>% round(2))) %>% select(DATE, WET) %>% distinct()
  SWAP_INPUT_DF <- left_join(SWAP_INPUT_DF, WET, by = "DATE")

  ### DATE and STATION
  SWAP_INPUT_DF$Station = "METNORDICvirtual"
  SWAP_INPUT_DF$DD = lubridate::day(SWAP_INPUT_DF$DATE) %>% stringr::str_pad(width = 2, side = "left", pad = "0")
  SWAP_INPUT_DF$MM = lubridate::month(SWAP_INPUT_DF$DATE) %>% stringr::str_pad(width = 2, side = "left", pad = "0")
  SWAP_INPUT_DF$YYYY = lubridate::year(SWAP_INPUT_DF$DATE) %>% as.character()

  # WRITING
  write_these <- c("Station", "DD", "MM", "YYYY", "RAD", "Tmin", "Tmax", "HUM", "WIND", "RAIN", "ETref", "WET")
  write_df <- SWAP_INPUT_DF %>% ungroup() %>% select(all_of(write_these))
  metadata <- paste("*", readLines(meta_path))
    writeLines(text = metadata, con = outpath)
  readr::write_csv(x = write_df, file = outpath, col_names = T, append = T)
  return(outpath)
}

